{"level":"error","message":"Failed to start server:","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"service":"shopify-insights-backend","stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (d:\\Shopify\\shopify-insights-platform\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (d:\\Shopify\\shopify-insights-platform\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorEvent (d:\\Shopify\\shopify-insights-platform\\backend\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:524:28)\n    at Socket.reportStreamError (d:\\Shopify\\shopify-insights-platform\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2025-09-11 11:52:03"}
{"level":"error","message":"Failed to start server:","name":"SequelizeConnectionRefusedError","original":{"code":"ECONNREFUSED"},"parent":{"code":"ECONNREFUSED"},"service":"shopify-insights-backend","stack":"SequelizeConnectionRefusedError\n    at Client._connectionCallback (d:\\Shopify\\shopify-insights-platform\\backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (d:\\Shopify\\shopify-insights-platform\\backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorEvent (d:\\Shopify\\shopify-insights-platform\\backend\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:524:28)\n    at Socket.reportStreamError (d:\\Shopify\\shopify-insights-platform\\backend\\node_modules\\pg\\lib\\connection.js:57:12)\n    at Socket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2025-09-11 11:55:13"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: listen EADDRINUSE: address already in use :::5000","port":5000,"service":"shopify-insights-backend","stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (d:\\Shopify\\shopify-insights-platform\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (d:\\Shopify\\shopify-insights-platform\\backend\\src\\server.js:108:9)","syscall":"listen","timestamp":"2025-09-11 11:58:11"}
{"address":"::","code":"EADDRINUSE","errno":-4091,"level":"error","message":"Uncaught Exception: listen EADDRINUSE: address already in use :::5000","port":5000,"service":"shopify-insights-backend","stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1937:16)\n    at listenInCluster (node:net:1994:12)\n    at Server.listen (node:net:2099:7)\n    at Function.listen (d:\\Shopify\\shopify-insights-platform\\backend\\node_modules\\express\\lib\\application.js:635:24)\n    at startServer (d:\\Shopify\\shopify-insights-platform\\backend\\src\\server.js:108:9)","syscall":"listen","timestamp":"2025-09-11 12:12:51"}
